# use actionlint to debug yaml https://rhysd.github.io/actionlint/
name: automate_time_sheet
on:
  schedule:
    - cron:  '17 9 * * *'
jobs:
  automate_time_sheet:
    runs-on: ubuntu-latest
    env:
      WHEREAMI: PRODUCTION
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    name: fill in time sheet
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Remove old logs and pngs
        run: |
          rm -f *.log
          rm -f *.png

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Installed package list
        run: apt list --installed

      - name: Remove default firefox
        run: sudo rm -fr /opt/firefox

      - name: Install firefox 100.0.2
        run: |
          echo "downloading firefox 100"
          wget "http://ftp.mozilla.org/pub/firefox/releases/100.0.2/linux-x86_64/en-US/firefox-100.0.2.tar.bz2"
          echo "extracting compressed file"
          sudo tar xjf firefox-*.tar.bz2
          echo "removing unneeded compressed file"
          sudo rm *.bz2
          echo "moving firefox"
          sudo mv firefox /opt
          echo "removing any existing firefox in /usr/bin"
          sudo rm /usr/bin/firefox
          echo "creating symbolic link"
          sudo ln -s /opt/firefox/firefox /usr/bin/firefox

      - name: Install all the dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: requirements.txt
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"

      - name: Run the automation script
        run: python main.py

      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: automation completed for today, please see attached logs
          add: .
