name: automate_time_sheet
on:
  schedule:
    - cron:  '10 9 * * *'
jobs:
  automate_time_sheet:
    runs-on: ubuntu-latest
    environment: production
    name: open repo
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Installed package list
        run: apt list --installed
      - name: Remove default firefox
        run: sudo apt purge firefox
      - name: Install a new firefox
        run: sudo apt install firefox
      - name: Install all the dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: requirements.txt
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      - name: Run the automation script
        env:
           USERNAME: ${{ secrets.USERNAME }}
           PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
